# uosc 配置
# 时间轴样式
timeline_size=40
timeline_persistency=paused,idle

# 控制栏
controls=menu,gap,subtitles,<has_many_audio>audio,<has_many_video>video,<has_many_edition>editions,<stream>stream-quality,cycle:toggle_on:show_danmaku@bili_live_danmaku:on=toggle_on/off=toggle_off?弹幕开关,gap,space,speed,shuffle,loop-playlist,loop-file,gap,prev,items,next,gap,fullscreen
controls_persistency=paused,idle

# 音量条
volume=right
volume_size=40
volume_persistency=paused,idle

# 顶栏
top_bar=no-border
top_bar_persistency=paused,idle

# 其他
autohide=yes
